# configuration for "master" branch
# build in Debug mode and Test

-
  branches:
    only:
    - master
    - nuspec

  version: 0.8.{build}
  configuration: Debug
  before_build:
  - nuget restore

# configuration for "release" branch
# build in Debug mode and Test

-
  branches:
    only:
    - release

  configuration: Release
  before_build:
    - nuget restore
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  nuget:
    account_feed: true
    project_feed: true    
  build:
    publish_nuget: true
    include_nuget_references: true
    verbosity: minimal
  deploy:
    provider: NuGet
    prerelease: true
    api_key:
      secure:  VupoidE3HdOx3mLhAdrOX/liMBaU122WL+0etvpc1fmlw6/8lE6W3TcLwByCFzhx
      artifact: /.*\.nupkg/
